export const ACTIONS = {
  SET_IS_LOADING: 'SET_IS_LOADING',
  SET_ERROR: 'SET_ERROR',

  SET_LOGIN: 'SET_LOGIN',
  SET_LOGIN_LOCAL: 'SET_LOGIN_LOCAL',
  SET_LOGOUT: 'SET_LOGOUT',
  UPDATE_DATA: 'UPDATE_DATA',
  UPDATE_PASSWORD: 'UPDATE_PASSWORD',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  SET_CART_ITEMS: 'SET_CART_ITEMS',
  SET_ORDERS: 'SET_ORDERS',
  SET_ORDER: 'SET_ORDER',

  SET_PRODUCTS: 'SET_PRODUCTS',
  SET_ARCHITECTURE_PRODUCTS: 'SET_ARCHITECTURE_PRODUCTS',
  SET_ART_PRODUCTS: 'SET_ART_PRODUCTS',
  SET_PRODUCT: 'SET_PRODUCT',

  SET_POSTS: 'SET_POSTS',
  SET_POST: 'SET_POST'
};
