export const ACTIONS = {
  SET_LOGIN: 'SET_LOGIN',
  SET_LOGIN_LOCAL: 'SET_LOGIN_LOCAL',
  SET_LOGOUT: 'SET_LOGOUT',

  SET_COLLECTIONS: 'SET_COLLECTIONS',

  SET_PRODUCTS: 'SET_PRODUCTS',
  SET_PRODUCT: 'SET_PRODUCT'
};
